### ISSUE TITLE
Raspberry Pi use both i2c-1 and i2c-0

### ISSUE THREAD

**Issue by GitBeagle** [pulquero/dbus-i2c#6]
I'm using an argon fan on my pi3 which uses i2c-1. I am also trying to use an INA226. Connecting both to i2c-1 works with short cables. Unfortunately, I need to use a ~1M cable for the ina226. Using a LTC4311 from Adafruit solves the longer cable issue but then the argon fan i2c does not work. Separating the two devices on the two i2c ports would solve my problem but I don't know how to get the DC System Aggregator to recognize i2c-0. I have enabled i2c-0 in config.txt and it shows up with address 0x50.

I am controlling the fan through node-red using i2cset. I just need dbus-i2c to use i2c-0 instead of i2c-1.

Is this possible with the current version of you software? Can you point me in the right direction?

**Comment by pulquero** [comment]
Yes, it is possible, in the json config files there should be a bus option that you can change.

**Comment by GitBeagle** [comment]
Thanks for the quick response. I found the json file at /data/setupOptions/dbus-i2c and changed the bus and other info to match my configuration. Waiting on a delivery to resume testing.
